### ISSUE TITLE
Bug with the decimal bar effects

### ISSUE THREAD

**Issue by bernardstef** [NeariX67/WLED_Clock#1]
Hi !

First , thanks for the excellent work ! It gives a nice addition to the wall clock !

I use 9 LEDs per strip, but I have a problem where the decimal bar (at 10 am for example) applies the palette of the downlights (not sure if i'm really clear! )

For example, when I set white for the downlight, it also applies to the "1" bar when it's 10:00 for example.
When I set red for the hours palette, the bar stays white and only the zero gets red.

I think the problem is somewhere here, but I can't pinpoint it ... Do you have any idea ?

Thanks a lot again !

`uint16_t WS2812FX::mode_clock(void) {

  uint8_t timeHour = hour(local) % 12;
  if(timeHour == 0) timeHour = 12;
  uint8_t timeMinute = minute(local);
  uint8_t numberOfSegments = 3;     //1.5x Hours, 2x Minutes, because 12 hour format
  uint8_t ledsPerSegment = 9;       //5 LEDs per Segmentfraction (7 Segment with each 3 LEDs = 21 LEDs)

  uint8_t digits[4];
  digits[0] = timeHour / 10;
  digits[1] = timeHour % 10;
  digits[2] = timeMinute / 10;
  digits[3] = timeMinute % 10;

  uint8_t index = 0;
  uint8_t usedIndex = 0;        //Used for better Color Palette usage
  uint8_t counter = (now * ((SEGMENT.speed >> 2) + 2)) & 0xFFFF;
  
  for (int i = numberOfSegments; i > 0; i--) {
    for (int j = 0; j < 7; j++) {
      for (int k = 0; k < ledsPerSegment; k++) {
        if(segmentArray[digits[i]+1][j]) {
          usedIndex++;
          if(i == 3 || i == 2) {      //Minutes
            setPixelColor(index, color_from_palette(usedIndex*map(SEGMENT.intensity, 0, 255, 0, 25)+(now / map(SEGMENT.speed, 0, 255, 400, 5)), false, true, 0));
          }
          else if(i == 1) {                      //Hours
            setPixelColor(index, color_from_palette(usedIndex*map(SEGMENT.intensity, 0, 255, 0, 25)+(now / map(SEGMENT.speed, 0, 255, 400, 5)), false, true, 1));
          }
        }
        else {
          setPixelColor(index, 0);
        }
        index++;
      }
    }
  }
  if(timeHour >= 10) {
    for(uint8_t i = 0;i < 2*ledsPerSegment;i++) {
      setPixelColor(index+i, color_from_palette(usedIndex*map(SEGMENT.intensity, 0, 255, 0, 25)+(now / map(SEGMENT.speed, 0, 255, 400, 5)), false, true, 1));
    }
  }
  else {
    index += 2*ledsPerSegment;
  }
  for(int i = index; i < SEGLEN;i++) {
    setPixelColor(i, SEGCOLOR(2));
  }

  return FRAMETIME;
}`

**Comment by NeariX67** [comment]
Hey, i just discovered a issue related to that "1" bar, but i guess its not what you mean. I fixed the issue where the 1 would stay on after switching from 12 am to 1 pm for example.

Please send me pictures of your clock, displaying your described issue so i know what the real issue is.
Cheers

**Comment by bernardstef** [comment]
Oh, actually I have this issue too, but as a workaround , Using Node-red, I turn the clock off (brightness 0) then back on every hour.

Here are some pictures. I have 9 leds per segment:
https://photos.app.goo.gl/kJGUQsNgGvUCrx2a8

Cheers !

**Comment by bernardstef** [comment]
Allright !
I understand your wiring, and indeed, you don't have the problem. Maybe I thinkered the settings too much, I'll reflash and tell you !
Thanks !!

**Comment by NeariX67** [comment]
This should be fixed already, please confirm

**Comment by bernardstef** [comment]
Thanks you !!
Sorry haven't had time lately to look about it, but I will try the fixes !
Thanks a lot again

**Comment by bernardstef** [comment]
I compiled and uploaded, can confirm, it works good now ! (decimal bar is not tied to the downlight color)
Cheers !
