### ISSUE TITLE
Incorrect first digit on 24h version

### ISSUE THREAD

**Issue by RedGuilhas** [NeariX67/WLED_Clock#10]
**Describe the bug**
Hello,

I'm not getting the correct first digit. The strips all work correct if I turn them all on on Wled.

The time was 07:53 at the time of the photo but as you can see the 0 is not displaying correctly

![image](https://user-images.githubusercontent.com/41800494/148049041-12b6a145-44fc-416b-b001-fcbbea323e34.png)

I flashed the /NeariX67/WLED_Clock/tree/master/wled00/wled00.ino.d1_mini.bin on a D1 Mini and everything works except the first digit.

Thank you for your help!

**Comment by NeariX67** [comment]
Hey, can you try to set the tertiary color to something other than orange? I suspect that you are using the am/pm mode instead of 24h. Please confirm that you have enabled the 24h format in the time settings.

**Comment by RedGuilhas** [comment]
> Hey, can you try to set the tertiary color to something other than orange? I suspect that you are using the am/pm mode instead of 24h. Please confirm that you have enabled the 24h format in the time settings.

I've confirmed in the word app that I'm using 24h format.

![IMG_20220106_000116](https://user-images.githubusercontent.com/41800494/148307256-d24c8794-f8fc-4fe5-b160-cf0512e3d6af.jpg)

In this picture it should be 00:01. What could be wrong here?

**Comment by torn8o** [comment]
Could you double check the wiring? If the middle section on the first digit is wrong it could be the issue.  You can set wled to solid and set the led count to test the order of the leds.

**Comment by torn8o** [comment]
Your first digit should only be a one it wouldn’t need to make any other number except zero and one. Would also mean u don’t need the leds on the middle of first digit.

**Comment by RedGuilhas** [comment]
> Your first digit should only be a one it wouldn’t need to make any other number except zero and one. Would also mean u don’t need the leds on the middle of first digit.

I understand, but I would like to have a 24h clock so I need to have a "2" in the frst digit to make the 20, 21, 22 and 23 and for that I need to the strip in the middle. Maybe I'm misunderstanding something here.

**Comment by NeariX67** [comment]
Your hardware setup is messed up (didn't notice it in the beginning). The two hour digits share the same
 2 segments. And that can't work.

<img width="932" alt="Screenshot 2022-01-06 at 09 35 52" src="https://user-images.githubusercontent.com/31779313/148353860-45543027-5de2-46fb-87fe-10fd950f675f.png">

**Comment by RedGuilhas** [comment]
> Your hardware setup is messed up (didn't notice it in the beginning). The two hour digits share the same 2 segments. And that can't work.
> 
> <img alt="Screenshot 2022-01-06 at 09 35 52" width="932" src="https://user-images.githubusercontent.com/31779313/148353860-45543027-5de2-46fb-87fe-10fd950f675f.png">

I see. Which means I need to have another row of plastic supports and a bigger wood board.. well I guess I will stay with the am/pm clock then.
Thanks for the help.
