### ISSUE TITLE
24 h Version 

### ISSUE THREAD

**Issue by 5ilia5** [NeariX67/WLED_Clock#2]
hello, can you please provide the code for the 24 hour variant or show what needs to be changed? I tried to change the code. the hours are also really timed. unfortunately the last number (minutes) is always zero. me and all europeans would be very grateful to you. best greetings

**Comment by NeariX67** [comment]
Yeah no problem. Currently working on it, expect an update in the next 48 hours

**Comment by NeariX67** [comment]
The "develop" branch features the updates. Check it out if it works, you may need to reconfigure the led count. As i am still at work, i haven't tested anything yet. Will update here in about 4 hours.

**Comment by 5ilia5** [comment]
hello, first of all thank you very much. I've tested the changes. but without success. all variants with 24 h and or seconds have some errors. a segment is shown before the first number of minutes. this shows the last effect. the seconds are between hours and minutes and work as desired. The numbers displayed do not make any sense. in addition, the 1 of the 12 h variant would be added at the end. (1xx: yyz) is output where x and y are not correct.

**Comment by NeariX67** [comment]
Oh damn you are right. As i dont have a proper 7 segment clock around, i can't properly test it. I just use a regular straight led strip to test. I guess i need to rebuild my clock to allow proper testing soon. What would really help is a video showing the misbehaviour and a correct time next to it, so i can see what it should display. If you have Discord, please join the WLED server which is linked at the bottom of the readme.

**Comment by NeariX67** [comment]
And i don't know if you have tested the current master branch or the old develop branch. Please confirm

**Comment by 5ilia5** [comment]
hello, i didn't build the layout either, just put the led strip on the floor. the original verse can also be recognized if you know how to read it. I will try to build a dummy for testing at the weekend. I think you can also test that with your watch. the seconds seem to work inf are also not that important. if the code is correct for 24 hours in your variant, the last segment should show a 1 at 10:00 p.m. and the next 5 downlights from the following 5 then show again. so you could see if it worked
Ps: i tested the develop branch

**Comment by 5ilia5** [comment]
Sorry, at 22:00 the Last Segment Must Show 10 LEDs than 5 Downlights off and than 5 downlights on to Show the beginnging of the 2

**Comment by NeariX67** [comment]
I don't know if i made relevant changes in the master branch, but it worth checking out. I will rewire my current clock so i can properly test my code. It should be done by this weekend.

**Comment by 5ilia5** [comment]
one more quick question. is it correct that in the code everywhere USE_24H_FORMAT. Is used. Doesn't this mean that the mapping of the 12 hours is also used for the 24 hours?

**Comment by NeariX67** [comment]
I don't quite get your question, but yes that define USE_24H_FORMAT is used to differentiate between the 12h and 24h-format to save some duplicated code.

**Comment by 5ilia5** [comment]
Hello, I have now set up a test and found the following. There are currently 4 segments and the downlights. All sizes and order are correct. When AB:CD is displayed, D is always zero A, B, C are offset by one segment, e.g. 21:34 then the output is 13:40. with a time of 23:42 the output is 34:20. I have not checked the seconds. I hope you can find the error with this description.
Many thanks

**Comment by NeariX67** [comment]
I'm very proud its just this error. I already know what the mistake is as i already found it earlier, but wanted to wait for any other issues. I will fix this tomorrow.

**Comment by 5ilia5** [comment]
hello, now there is a new problem, when selecting the clock dancing shadows are always displayed. I made the changes you made yesterday myself, but then there were other problems.

**Comment by 5ilia5** [comment]
the error is in FX.h line106. the effect can now be started. unfortunately the segments are still offset by 1. e.g. 21:32 is displayed as 13:20.

**Comment by NeariX67** [comment]
Yeah i found that error very quickly. I just now had my clock nearby to actually test my code. Everything should work now as expected. I removed the define 24h format thing, because there is a setting in the time and macros page called "use 24h format". I used that to change the effect behaviour.

**Comment by 5ilia5** [comment]
everything works as it should. Thank you for making WLED even more useful.

**Comment by NeilvdM** [comment]
I finished all the printing and will attempt the 24H setup. Crossing fingers!
Thank you in advance @NeariX67 for this WLED version!

**Comment by NeariX67** [comment]
The only thing that could make a lot of mess is wiring the leds in the wrong order. It gets rather complicated to correct it in software if you don't use the same order for your digits, so just make the hardware the right way. If you consider a different order as a better layout for your clock, use that, but use the same order for all digits... The order is easily editable

**Comment by NeilvdM** [comment]
I have a question, I tried to find out from the code, but couldn't find the mention of the pins.
Im using the D1mini, which pins do I need to use for the clock LEDs and which for the downlights? 
Or does it stay the same as with the Standard WLED connections?

**Comment by NeilvdM** [comment]
I just realized something .. I would not even require the clock module anymore, am I correct?
I build/connect this up as any other WLED connection I have made before, then in WLED settings, select the clock?

**Comment by NeariX67** [comment]
Pins are configured in npbwrapper.h, everything you need to know is in the normal WLED repository and in the readme of this fork. There is an effect called "Clock" so need to set something in the settings except enable ntp and the 24h format.
No need to configure the code.

**Comment by NeilvdM** [comment]
ok, this might be a stupid question, but I am stuck .. 
when I download the zip file with the code and I open it in Arduino, none of your changes are there regarding the 24H clock.\
do I manually have to copy and paste your changes or am I just doing things wrong?

**Comment by NeilvdM** [comment]
Hey @NeariX67 , I have another question. 
So with the 24h version, I have 252 LEDs, 9 per strip, and should have 14 down lights. Where/how do I tell WLED that I have 14 down lights?

**Comment by NeariX67** [comment]
Hey @NeilvdM, as _ledsPerSegment_ is already 9 in this repository, you don't need to change anything in the code. Just enable the 24h format in the NTP settings and you are good to go. 252 LEDs for the clock and 14 LEDs as down lights will equal 266 LEDs, so just set this as your pixel count in the wled settings and you are good to go. My effect calculates how many leds are needed (in your case 4*7*9 = 252) and uses every pixel that will come after that as a downlight. So 253-262 will be downlights.
