### ISSUE TITLE
LED Wiring Sequence

### ISSUE THREAD

**Issue by ar3mia** [NeariX67/WLED_Clock#3]
Hi, first of all thanks for the development you did for this project. 
I have a question regarding the order of the LED segments.... 
Which order do I wire the "Colon Separator" and the "Downlight" LEDs? 
I am assuming they are wired after the "time digits", but which ones go first, the downlight or the colon?? 
and is there a config for the number of "downlight" leds?

**Comment by NeariX67** [comment]
The colon separator goes between the hours and minutes so [using this image](https://youtu.be/8E0SeycTzHw?t=491) that would be between 14 and 15. Any LEDs that will come after the very last part (part 23 using that image) will be used as a downlight. Or as i wrote in #2: 

> 252 LEDs for the clock and 14 LEDs as down lights will equal 266 LEDs, so just set this as your pixel count in the wled settings and you are good to go. My effect calculates how many leds are needed (in your case 4x7x9 = 252) and uses every pixel that will come after that as a downlight. So 253-262 will be downlights.

But make sure you enable the colon separator as described in the readme and set the correct led count.

**Comment by ar3mia** [comment]
Thanks
