### ISSUE TITLE
Support for other 7 segment clocks

### ISSUE THREAD

**Issue by sarreck** [NeariX67/WLED_Clock#5]
Thanks for your work on this great mod. 

I was hoping to modify the code to work with a slightly different wiring setup used in the Ivan Miranda Giant clock - [here](https://www.youtube.com/watch?v=4z82I-032zs)

The following is how each digit is wired with two dots between the second and third.  

![LED-WIRE](https://user-images.githubusercontent.com/6550017/104787647-2df31f00-57e4-11eb-8f16-ef3c8c61d07a.png)

My setup has 9 LEDS per segment with 3 for each dot giving a total of 258 LEDs.

I was hoping to simply not use the down-light component, 

I am guessing this requires modification of the array at Line 3724 and i was hoping that you could provide some guidance on how to proceed. 

Thanks

**Comment by NeariX67** [comment]
So, this 2D-Array is indeed for the order of your leds. The first dimension is "All leds off", followed by 0, 1, 2, ....
And the second dimension is a boolean array of each segment.

Your array would look like this:
```c++
const boolean segmentArray[11][7] = {{0, 0, 0, 0, 0, 0, 0}, {1, 1, 1, 1, 1, 1, 0}, {0, 0, 1, 1, 0, 0, 0},
                                     {0, 1, 1, 0, 1, 1, 1}, {0, 1, 1, 1, 1, 0, 1}, {1, 0, 1, 1, 0, 0, 1},
                                     {1, 1, 0, 1, 1, 0, 1}, {1, 1, 0, 1, 1, 1, 1}, {0, 1, 1, 1, 0, 0, 0},
                                     {1, 1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 0, 1}

```

**Comment by sarreck** [comment]
Thanks for your help.

I have made the changes but i am having some issues with the digits displaying correctly.

At 11:40am it is displaying the following:

![clock1](https://user-images.githubusercontent.com/6550017/104828046-6c0e4280-58b9-11eb-9b60-550cf5d76fb4.png)

The WLED config for colours is:

![wled1](https://user-images.githubusercontent.com/6550017/104828077-9c55e100-58b9-11eb-894e-6f5f93a98381.png)
 
So there are no hours displaying, minutes is limited to the first digit and downlights are displaying even though there should not be any LEDs remaining for them. 

WLED LEDs are configured as:
![LED](https://user-images.githubusercontent.com/6550017/104828115-f2c31f80-58b9-11eb-85de-6120cb3af784.png)

My code has been modified as follows (after commenting out the other segments):

```
//Ivan Miranda Giant Clock
const boolean segmentArray[11][7] = {{0, 0, 0, 0, 0, 0, 0}, {1, 1, 1, 1, 1, 1, 0}, {0, 0, 1, 1, 0, 0, 0},
                                     {0, 1, 1, 0, 1, 1, 1}, {0, 1, 1, 1, 1, 0, 1}, {1, 0, 1, 1, 0, 0, 1},
                                     {1, 1, 0, 1, 1, 0, 1}, {1, 1, 0, 1, 1, 1, 1}, {0, 1, 1, 1, 0, 0, 0},
                                     {1, 1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 0, 1}
};


//Comment or uncomment this for your setup!
#define USE_COLON_SEPARATOR

uint16_t WS2812FX::mode_clock(void) {


  uint8_t timeSecond = second(localTime);
  uint8_t timeMinute = minute(localTime);

  uint8_t ledsPerSegment = 63;       //9 LEDs per Segmentfraction (7 Segment with each 9 LEDs = 63 LEDs)
  uint8_t numberOfSegments = 4;     //2x Hours, 2x Minutes

  uint8_t timeHour = 0;             //Bypass compiler error
  uint8_t limit = 0;                //Bypass compiler error, sets it according to 12/24h format

  if(!useAMPM) {
    limit = 0;
    timeHour = hour(localTime);
  }
  else {
    limit = 1;
    timeHour = hour(localTime) % 12;
    if(timeHour == 0) timeHour = 12;
  }

  #ifdef USE_COLON_SEPARATOR
    uint8_t ledsPerDot = 3;         //1 LED per seconds dot, so 2 in total
    #define dotColor 0xFFFFFF
  #endif
```


Any ideas?

Thanks

**Comment by NeariX67** [comment]
uint8_t ledsPerSegment = 63; 

should be 9

**Comment by sarreck** [comment]
hmm, Interesting.

Making that change has now set all LEDs are part of the down-light colour. 

This is the current state of the modified section:
```

//Comment or uncomment this for your setup!
#define USE_COLON_SEPARATOR

uint16_t WS2812FX::mode_clock(void) {


  uint8_t timeSecond = second(localTime);
  uint8_t timeMinute = minute(localTime);

  uint8_t ledsPerSegment = 9;       //9 LEDs per Segmentfraction (7 Segment with each 9 LEDs = 63 LEDs)
  uint8_t numberOfSegments = 4;     //2x Hours, 2x Minutes

  uint8_t timeHour = 0;             //Bypass compiler error
  uint8_t limit = 0;                //Bypass compiler error, sets it according to 12/24h format

  if(!useAMPM) {
    limit = 0;
    timeHour = hour(localTime);
  }
  else {
    limit = 1;
    timeHour = hour(localTime) % 12;
    if(timeHour == 0) timeHour = 12;
  }

  #ifdef USE_COLON_SEPARATOR
    uint8_t ledsPerDot = 3;         //1 LED per seconds dot, so 2 in total
    #define dotColor 0xFFFFFF
  #endif
```

If I disable  #define USE_COLON_SEPARATOR  it mostly works, however half the digits are shifted by the 9 leds (and the downlight controls the last 9 leds).

My hardware config uses a colon with two dots (3 leds each) between the hours and minutes.

**Comment by NeariX67** [comment]
Hmm weird. But it somehow works with others setup

**Comment by sarreck** [comment]
It is possible i have a wiring issue. 

With the colon separator, is the code expecting it to be wired between the hours and minutes or at the end of the string?
What colour would it be using?

**Comment by NeariX67** [comment]
it should be between hours and minutes, color is defined in 

    #define dotColor 0xFFFFFF

line 3758

**Comment by sarreck** [comment]
I have managed to get everything working fine by re-wiring the two dots to the end of the string and controlling them with the down-light colour. For my use case this is perfect and even gives me a little more functionality. 

![clock2](https://user-images.githubusercontent.com/6550017/104831293-953fca80-58db-11eb-8356-5fe12e37f6b8.png)

I suspect you are right that the issue using "USE_COLON_SEPARATOR" is something that I am doing. When i enable this the first 1 or 2 LEDs use the minute colour and the rest are controlled as a down-light.

Thanks for your help and for publishing this great software.
