### ISSUE TITLE
First digit only has single color using color presets

### ISSUE THREAD

**Issue by TTDARK** [NeariX67/WLED_Clock#6]
First of all thanks for the great work! Otherwise using multiple boards with inbuilt segments would have been the only other solution.

**Describe the bug**
When using "Clock" effect with a preset color pallet, e.g. "Yelmag", the first (left) digit has one single color, while the other 3 digits have the expected color effects.
I have checked the wiring and functionality of my LED strips with the rainbow effect. Every LED is addressable and function normally.

**To Reproduce**
In 12h format. Choose Clock, then instead of using 2 colors (one for hh and one for mm), choose any preset color pallet from below. Maybe select Yelmag for the most observable effect.

**Expected behavior**
Every digit should have the selected color effect applied.

**WLED version**
 - Board: [Sonoff Basic R2]
 - Version [10.2]
 - Format [self-compiled]

**Additional context**
Here are some pictures.
[![sztXnI.md.jpg](https://s3.ax1x.com/2021/01/27/sztXnI.md.jpg)](https://imgchr.com/i/sztXnI)
[![sztLjA.md.jpg](https://s3.ax1x.com/2021/01/27/sztLjA.md.jpg)](https://imgchr.com/i/sztLjA)
[![sztqcd.md.jpg](https://s3.ax1x.com/2021/01/27/sztqcd.md.jpg)](https://imgchr.com/i/sztqcd)

Thank you for your help!

**Comment by NeariX67** [comment]
Sounds like an easy fix. I'm on it.

**Comment by NeariX67** [comment]
There was just one line missing. Fixed it and it should work now. Remember to include this new commit in your fork. Have a nice day and stay safe! =)

**Comment by NeariX67** [comment]
I have no idea, as i never dealt with those. Maybe try a shot in the official WLED Discord.
